name: Health Check

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: Check Backend Status
      with:
        url: ${{ secrets.url }}
        endpoint: ${{ secrets.endpoint }}
      run: curl -f --no-progress-meter "$url$endpoint"
